modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory (24 is current forge version)

credits="Thanks to kwpugh for the original Gobber2 mod." #optional

authors="Chuong" #optional

[[mods]] #mandatory
modId="ring_of_repair" #mandatory
version="1.0.0" #mandatory
displayName="Ring of Repair" #mandatory
description='''
A simple mod that adds a ring that repairs items in your inventory.
'''


[[dependencies.ring_of_repair]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.ring_of_repair]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
